# Generated by Django 4.2.28 on 2026-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_sale_price_remove_sale_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Timbre fiscal (DA)'),
        ),
    ]
